name: Deploy Storybook
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      # - name: Build Storybook
      #   run: npx storybook@latest init

      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./public
      # - name: Deploy GitHub Pages site
      #   uses: actions/deploy-pages@v1.2.9
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy Storybook to GitHub Pages
        # You may pin to the exact commit or the version.
        # uses: bitovi/github-actions-storybook-to-github-pages@c7d2a479f2ec3d87d1131357f328e0e40c60da20
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.0
